bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation project(":domain")
    implementation project(":support:logging")
    implementation project(":support:common")
    implementation project(":infrastructure:redis")

    testImplementation project(":tests:api-docs")

    implementation 'org.springframework.boot:spring-boot-starter-web'

    // craw
    implementation 'com.microsoft.playwright:playwright:1.48.0'
}
